# Generated by Django 5.0.6 on 2024-06-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_name', models.CharField(max_length=20)),
                ('cake_price', models.IntegerField()),
                ('cake_stock', models.IntegerField()),
                ('cake_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
