# Generated by Django 5.0.6 on 2024-07-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_cart_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_total',
        ),
    ]
